version: "3.7"
services:
  app:
    build:
      context: ../
      dockerfile: ./docker/DockerFile 
    ports:
      - "4335:4335"
    environment: 
      - FOO=Bar
    volumes:
      - ../app/:/app/
      - ../data:/data
      - ./results:/results
 
    networks:
      - elk

networks:
  elk:
    driver: bridge