version: "3.7"
services:
  app:
    build:
      context: ../
      dockerfile: ./docker/DockerFile 
    ports:
      - "4335:4335"
    environment: 
      - FOO=Bar
      - ES_URL=http://elasticsearch:9200
      - PYTHONUNBUFFERED=1
    volumes:
      - ../app/:/app/
      - ../data:/data
      - ../results:/results
    entrypoint:
      ["python3", "/app/parse_pdf.py"]
    networks:
      - elk


networks:
  elk:
    driver: bridge